#mirror 'http://www.cpan.org';
#mirror 'http://pan.hachiojipm.org';
requires 'AnyEvent';
requires 'FindBin';
requires 'Log::Minimal';
requires 'Unruly';
requires 'URL::Encode';
requires 'Web::Query';
requires 'Text::MeCab';
requires 'Encode', '2.60';
